CREATE TABLE usuario (
    CODIGO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) UNIQUE,
    EMAIL VARCHAR(255) UNIQUE,
    SENHA VARCHAR(512),
    PERFIL VARCHAR(255),
    GUID VARCHAR(512)
);